import "./globals.css";
import UiProvider from "@/providers/UiProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="light text-foreground bg-background">
        <UiProvider>
       <main className="min-h-screen">
       {children}
       </main>
        </UiProvider>
      </body>
    </html>
  );
}
