import "./globals.css";
import UiProvider from "@/providers/UiProvider";
import ConditionalHeader from "@/components/ConditionalHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background overflow-x-hidden">
        <UiProvider>
<ConditionalHeader/>
       <main className="min-h-screen">
       {children}

       </main>
        </UiProvider>
      </body>
    </html>
  );
}
